export const UPDATE_LOCATION_REQUEST = 'UPDATE_LOCATION_REQUEST';
export const UPDATE_LOCATION_SUCCESS = 'UPDATE_LOCATION_SUCCESS';
export const UPDATE_LOCATION_FAIL = 'UPDATE_LOCATION_FAIL';

export const UPDATE_LOCATION_IMG_REQUEST = 'UPDATE_LOCATION_IMG_REQUEST';
export const UPDATE_LOCATION_IMG_SUCCESS = 'UPDATE_LOCATION_IMG_SUCCESS';
export const UPDATE_LOCATION_IMG_FAIL = 'UPDATE_LOCATION_IMG_FAIL';

export const DETAIL_LOCATION_REQUEST = 'DETAIL_LOCATION_REQUEST';
export const DETAIL_LOCATION_SUCCESS = 'DETAIL_LOCATION_SUCCESS';
export const DETAIL_LOCATION_FAIL = 'DETAIL_LOCATION_FAIL';



