export const UPDATE_BOOK_ROOM_REQUEST = 'UPDATE_BOOK_ROOM_REQUEST';
export const UPDATE_BOOK_ROOM_SUCCESS = 'UPDATE_BOOK_ROOM_SUCCESS';
export const UPDATE_BOOK_ROOM_FAIL = 'UPDATE_BOOK_ROOM_FAIL';

export const DETAIL_BOOK_ROOM_REQUEST = 'DETAIL_BOOK_ROOM_REQUEST';
export const DETAIL_BOOK_ROOM_SUCCESS = 'DETAIL_BOOK_ROOM_SUCCESS';
export const DETAIL_BOOK_ROOM_FAIL = 'DETAIL_BOOK_ROOM_FAIL';





