export const SET_BOOK_ROOM_DETAIL = 'SET_BOOK_ROOM_DETAIL';

export const UPDATE_BOOK_ROOM_REQUEST = 'UPDATE_BOOK_ROOM_REQUEST';
export const UPDATE_BOOK_ROOM_SUCCESS = 'UPDATE_BOOK_ROOM_SUCCESS';
export const UPDATE_BOOK_ROOM_FAIL = 'UPDATE_BOOK_ROOM_FAIL';

export const UPDATE_BOOK_ROOMIMG_REQUEST = 'UPDATE_BOOK_ROOMIMG_REQUEST';
export const UPDATE_BOOK_ROOMIMG_SUCCESS = 'UPDATE_BOOK_ROOMIMG_SUCCESS';
export const UPDATE_BOOK_ROOMIMG_FAIL = 'UPDATE_BOOK_ROOMIMG_FAIL';





