export const MANAGE_ROOM_REQUEST = 'MANAGE_ROOM_REQUEST';
export const MANAGE_ROOM_SUCCESS = 'MANAGE_ROOM_SUCCESS';
export const MANAGE_ROOM_FAIL = 'MANAGE_ROOM_FAIL';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const DELETE_ROOM_FAIL = 'DELETE_ROOM_FAIL';
