export const MANAGE_LOCATION_REQUEST = 'MANAGE_LOCATION_REQUEST';
export const MANAGE_LOCATION_SUCCESS = 'MANAGE_LOCATION_SUCCESS';
export const MANAGE_LOCATION_FAIL = 'MANAGE_LOCATION_FAIL';

export const DELETE_LOCATION_REQUEST = 'DELETE_LOCATION_REQUEST';
export const DELETE_LOCATION_SUCCESS = 'DELETE_LOCATION_SUCCESS';
export const DELETE_LOCATION_FAIL = 'DELETE_LOCATION_FAIL';
