export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const UPDATE_USER_IMG_REQUEST = 'UPDATE_USER_IMG_REQUEST';
export const UPDATE_USER_IMG_SUCCESS = 'UPDATE_USER_IMG_SUCCESS';
export const UPDATE_USER_IMG_FAIL = 'UPDATE_USER_IMG_FAIL';

export const DETAIL_USER_REQUEST = 'DETAIL_USER_REQUEST';
export const DETAIL_USER_SUCCESS = 'DETAIL_USER_SUCCESS';
export const DETAIL_USER_FAIL = 'DETAIL_USER_FAIL';




