export const DETAIL_BOOK_ROOM_REQUEST = 'DETAIL_BOOK_ROOM_REQUEST';
export const DETAIL_BOOK_ROOM_SUCCESS = 'DETAIL_BOOK_ROOM_SUCCESS';
export const DETAIL_BOOK_ROOM_FAIL = 'DETAIL_BOOK_ROOM_FAIL';

export const DETAIL_ROOM_REQUEST = 'DETAIL_ROOM_REQUEST';
export const DETAIL_ROOM_SUCCESS = 'DETAIL_ROOM_SUCCESS';
export const DETAIL_ROOM_FAIL = 'DETAIL_ROOM_FAIL';




