export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_SUCCESS = 'UPDATE_ROOM_SUCCESS';
export const UPDATE_ROOM_FAIL = 'UPDATE_ROOM_FAIL';

export const UPDATE_ROOM_IMG_REQUEST = 'UPDATE_ROOM_IMG_REQUEST';
export const UPDATE_ROOM_IMG_SUCCESS = 'UPDATE_ROOM_IMG_SUCCESS';
export const UPDATE_ROOM_IMG_FAIL = 'UPDATE_ROOM_IMG_FAIL';

export const DETAIL_ROOM_REQUEST = 'DETAIL_ROOM_REQUEST';
export const DETAIL_ROOM_SUCCESS = 'DETAIL_ROOM_SUCCESS';
export const DETAIL_ROOM_FAIL = 'DETAIL_ROOM_FAIL';



