export const SET_USER_DETAIL = 'SET_USER_DETAIL';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const UPDATE_USERIMG_REQUEST = 'UPDATE_USERIMG_REQUEST';
export const UPDATE_USERIMG_SUCCESS = 'UPDATE_USERIMG_SUCCESS';
export const UPDATE_USERIMG_FAIL = 'UPDATE_USERIMG_FAIL';





