export const ADD_NEW_BOOK_ROOM_REQUEST = 'ADD_NEW_BOOK_ROOM_REQUEST';
export const ADD_NEW_BOOK_ROOM_SUCCESS = 'ADD_NEW_BOOK_ROOM_SUCCESS';
export const ADD_NEW_BOOK_ROOM_FAIL = 'ADD_NEW_BOOK_ROOM_FAIL';

