export const MANAGE_BOOK_ROOM_REQUEST = 'MANAGE_BOOK_ROOM_REQUEST';
export const MANAGE_BOOK_ROOM_SUCCESS = 'MANAGE_BOOK_ROOM_SUCCESS';
export const MANAGE_BOOK_ROOM_FAIL = 'MANAGE_BOOK_ROOM_FAIL';

export const DELETE_BOOK_ROOM_REQUEST = 'DELETE_BOOK_ROOM_REQUEST';
export const DELETE_BOOK_ROOM_SUCCESS = 'DELETE_BOOK_ROOM_SUCCESS';
export const DELETE_BOOK_ROOM_FAIL = 'DELETE_BOOK_ROOM_FAIL';
